/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lance_jni_MathKit */

#ifndef _Included_com_lance_jni_MathKit
#define _Included_com_lance_jni_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lance_jni_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lance_jni_MathKit_square
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_lance_jni_MathKit
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lance_jni_MathKit_test
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
